/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GGhslugRouteImport } from './routes/g.$ghslug'
import { Route as HackathonsIndexRouteImport } from './routes/hackathons.index'
import { Route as HackathonsSlugRouteImport } from './routes/hackathons.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GGhslugRoute = GGhslugRouteImport.update({
  id: '/g/$ghslug',
  path: '/g/$ghslug',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIndexRoute = HackathonsIndexRouteImport.update({
  id: '/hackathons/',
  path: '/hackathons/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsSlugRoute = HackathonsSlugRouteImport.update({
  id: '/hackathons/$slug',
  path: '/hackathons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/g/$ghslug': typeof GGhslugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/hackathons/': typeof HackathonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/g/$ghslug': typeof GGhslugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/hackathons': typeof HackathonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/g/$ghslug': typeof GGhslugRoute
  '/hackathons/$slug': typeof HackathonsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/hackathons/': typeof HackathonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/blog/$slug'
    | '/g/$ghslug'
    | '/hackathons/$slug'
    | '/blog/'
    | '/hackathons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/blog/$slug'
    | '/g/$ghslug'
    | '/hackathons/$slug'
    | '/blog'
    | '/hackathons'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/blog/$slug'
    | '/g/$ghslug'
    | '/hackathons/$slug'
    | '/blog/'
    | '/hackathons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GGhslugRoute: typeof GGhslugRoute
  HackathonsSlugRoute: typeof HackathonsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HackathonsIndexRoute: typeof HackathonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$ghslug': {
      id: '/g/$ghslug'
      path: '/g/$ghslug'
      fullPath: '/g/$ghslug'
      preLoaderRoute: typeof GGhslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/': {
      id: '/hackathons/'
      path: '/hackathons'
      fullPath: '/hackathons/'
      preLoaderRoute: typeof HackathonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$slug': {
      id: '/hackathons/$slug'
      path: '/hackathons/$slug'
      fullPath: '/hackathons/$slug'
      preLoaderRoute: typeof HackathonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  BlogSlugRoute: BlogSlugRoute,
  GGhslugRoute: GGhslugRoute,
  HackathonsSlugRoute: HackathonsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  HackathonsIndexRoute: HackathonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
